trigger:
- main

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

name: $(Build.Reason)_commit-$(Build.SourceVersion)_$(Date:yyyyMMdd_HHmmss)

jobs:
- job: Build
  displayName: 'Build and pack projects'
  steps:
    - template: azure-project-build-steps.yml
      parameters:
        rootNamespace: 'RebrickableSharp.Client'

    - template: azure-project-build-steps.yml
      parameters:
        rootNamespace: 'RebrickableSharp.Client.Csv'