trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

name: $(Build.Reason)_commit-$(Build.SourceVersion)_$(Date:yyyyMMdd_HHmmss)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  
  semVerDate: $(Get-Date -Format yyyyMMdd+HHmmss)
  client: 'RebrickableSharp.Client'

steps:
  - task: NuGetToolInstaller@1
  
  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: PowerShell@2
    displayName: Update CSPROJ Files
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)\Build\update-csproj-versions.ps1'
      arguments: '-SrcDirectory $(System.DefaultWorkingDirectory) -BuildId $(Build.BuildId) -InformationalVersionSuffix "$(semVerDate)"'
      
  - task: PowerShell@2
    displayName: Update Build Number From Version
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)\Build\update-build-number-from-version.ps1'
      arguments: '-PathToCsprojFile $(System.DefaultWorkingDirectory)\$(client)\$(client).csproj'
      
  - task: DotNetCoreCLI@2
    displayName: Build Solution and create NuGet package
    inputs:
      command: 'pack'
      packagesToPack: '$(System.DefaultWorkingDirectory)\$(client)\$(client).csproj'
      versioningScheme: 'off'

  - task: VSBuild@1
    displayName: Build Solution
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
        PathtoPublish: '$(Build.ArtifactsStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'