trigger:
- main

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

name: $(Build.Reason)_commit-$(Build.SourceVersion)_$(Date:yyyyMMdd_HHmmss)

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  
  semVerDate: $(Get-Date -Format yyyyMMdd+HHmmss)
  rootNamespace: 'RebrickableSharp.Client'
  pathToLibDir: '$(System.DefaultWorkingDirectory)\$(rootNamespace)\'
  pathToLibCsproj: '$(pathToLibDir)$(rootNamespace).csproj'
  csvNamespace: 'RebrickableSharp.Client.Csv'
  pathToCsvDir: '$(System.DefaultWorkingDirectory)\$(csvNamespace)\'
  pathToCsvCsproj: '$(pathToCsvDir)$(csvNamespace).csproj'
  buildScripsPath: "$(System.DefaultWorkingDirectory)/Build"
  directoryBuildPropsPath: "$(System.DefaultWorkingDirectory)/Directory.Build.props"

steps:
  - task: NuGetToolInstaller@1
  
  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: PowerShell@2
    displayName: Update CSPROJ Files
    inputs:
      filePath: "$(buildScripsPath)/patch-build-props.ps1"
      arguments: '-DirectoryBuildPropsPath $(directoryBuildPropsPath) -BuildId $(Build.BuildId) -InformationalVersionSuffix "$(semVerDate)"'
      
  - task: PowerShell@2
    displayName: Update Build Number From Version
    inputs:
      filePath: "$(buildScripsPath)/update-build-number-from-version.ps1"
      arguments: "-PathToCsprojFile $(directoryBuildPropsPath)"
      
  - task: DotNetCoreCLI@2
    displayName: Build Solution And Create RebrickableSharp.Client NuGet Package
    inputs:
      command: 'pack'
      packagesToPack: '$(pathToLibCsproj)'
      versioningScheme: 'off'
      packDirectory: $(pathToLibDir)bin\$(buildConfiguration)

  - task: DotNetCoreCLI@2
    displayName: Build Solution And Create RebrickableSharp.Client.Csv NuGet Package
    inputs:
      command: 'pack'
      packagesToPack: '$(pathToCsvCsproj)'
      versioningScheme: 'off'
      packDirectory: $(pathToCsvDir)bin\$(buildConfiguration)

  - task: CopyFiles@2
    displayName: Copy RebrickableSharp.Client Bin To ArtifactsStagingDirectory
    inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: $(rootNamespace)\bin\$(BuildConfiguration)\**
        TargetFolder: '$(Build.ArtifactsStagingDirectory)'
        
  - task: CopyFiles@2
    displayName: Copy RebrickableSharp.Client.Csv Bin To ArtifactsStagingDirectory
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: $(csvNamespace)\bin\$(BuildConfiguration)\**
      TargetFolder: '$(Build.ArtifactsStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
        PathToPublish: '$(Build.ArtifactsStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'